[workspace]
resolver = "1"
members = ["egui-tracing", "examples/eframe", "examples/eframe-wasm32"]

[workspace.dependencies]
eframe = { version = "~0.30.0", default-features = false }
egui = { version = "~0.30.0", default-features = false }
